### ISSUE TITLE
Help Needed

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/octool#1]
Hi,
I'm finding this version confusing not sure where I'm going wrong

<img width="963" alt="Screenshot 2021-11-01 at 21 22 49" src="https://user-images.githubusercontent.com/2873112/139744206-6490f5b7-13a2-4c9c-b63b-378235d0b63f.png">

Thanks

**Comment by rusty-bits** [comment]
It looks like you're doing everything right.  From what I'm seeing it looks like you ran octool with a `-o 0.7.5` option., and I'm guessing if you didn't use the `-o 0.7.5` that octool guessed you had a version 0.7.4 config.plist  

When you get into the editor you can use the `V` command to tell octool what version of OpenCore you want to use at any time, so no need to use the `-o` option but it works fine either way.  

octool ran your config.plist through the 0.7.5 version of ocvalidate and found two quirks missing, what you can do with this new tool is navigate in to the Quirks sections and use the `m` command  
this will `merge` anything new in to your config.plist without changing any other settings  
you can use the `s` command at any time to `save` your config and also check it against ocvalidate at the same time  

the old `OC-tool` would try to update your config by itself, but the method it used wasn't the best and needed constant tweaks to the code to keep it working right.  
This new `octool` doesn't need any of that since it's reading the Configuration.tex and Sample.plist itself, and then using the ocvalidate tool as a check.  

I hope this helps.

**Comment by Blurayx** [comment]
Unfortunately, I still couldn't get it to work. It's a shame because I will have to stop using octool. Gone back to using OC-Gen for now.

Thanks for all your help.
