### ISSUE TITLE
Does it update config.plist?

### ISSUE THREAD

**Issue by Human79** [rusty-bits/octool#2]
Hello
I was wondering if this tool is able to update the config.plist like your previous tool?
Thanks.

**Comment by rusty-bits** [comment]
Hello Human7900,  
You can update your config with this tool, but it's not totally automatic like the last tool since that had a number of issues behind the scenes.  

Use `V` at any time to tell the tool what version of OpenCore you want it to use  
Use `s` at any time to save your progress and check your config.plist with ocvalidate at the same time  
Use `m` to automatically merge anything new into your config.plist from the Sample.plist  
Use `d` to delete anything no longer needed in your config.plist  
and as a last resort, use `r` to reset either one field or an entire section to what's in the Sample.plist  

As I learn more and get better at the Rust language I may automate things more, but for now people will need to do a little on their own.  I hope it works well for you.

**Comment by Human79** [comment]
Hi!
Thanks for the dedicated reply!
But I am still unable to make it work.
When I select quirks and press m, it doesn't do anything.
Attaching a screenshot for your reference.
![Screen Shot 2021-11-08 at 12 01 15 PM](https://user-images.githubusercontent.com/84245065/140705382-939be0b6-2cbe-4d68-b33f-2b20b75e5ebe.png)

**Comment by rusty-bits** [comment]
That looks fine to me.  There are only 20 Kernel quirks in OpenCore 0.7.5   
Did you check the other Quirks sections as well and try to merge them?  
You can use `f` to find `quirk` then use `n` to jump to the next and next etc.   
The `m` merge will only work on a highlighted section and it looks like there is nothing to merge into your Kernel>Quirks section

**Comment by Human79** [comment]
Thank you for the awesome support! It works!
Thank you for the great tool and all the best for the future updates!

**Comment by andrisi** [comment]
@rusty-bits could you elaborate on those problems encountered with automatic tool? The OpenCore guide specifically lists settings for various CPU-s, and then lspci lists devices, you you couléd pick the drivers. Am I naive? Seems like large number of people doing the same steps to get their system up and running, and most could be automated. Your tool takes an excellent direction with downloading what's needed, and this seems to be the next logical step. Building a database of what's needed where.
