### ISSUE TITLE
-o option doesn't seem to work

### ISSUE THREAD

**Issue by bkmartin** [rusty-bits/octool#4]
it seems to try to treat my -o 0.7.6 input as the config.plist argument

`
% ./octool -o 0.7.6

Did not find config at "/Users/bkmartin/opencore/octool/-o"
Using tool_config_files/OpenCorePkg/Docs/Sample.plist
`

**Comment by rusty-bits** [comment]
are you using the latest release version? - [currently 0.3.5](https://github.com/rusty-bits/octool/releases/tag/v0.3.5)  

unlike my older program, OC-tool, this version does not update itself automatically since it is a compiled binary so users will have to keep downloading the latest version for now  

I did have a release in there called "latest_dev_build", but I haven't been good about keeping it up to date

**Comment by bkmartin** [comment]
that was the problem.  i saw it doing it's git downloads and assumed it was updating the app as well.  thanks for the great tool
