### ISSUE TITLE
[Question] Error

### ISSUE THREAD

**Issue by Blurayx** [rusty-bits/octool#5]
1] Getting a config.plist error but boots without issues
2] can't find the listed errors in the config.plist
3] octool not generating a log file

<img width="572" alt="Screenshot 2022-03-08 at 01 46 38" src="https://user-images.githubusercontent.com/2873112/157150171-b803e657-95fd-4662-846e-53102d917a69.png">

Thanks

**Comment by rusty-bits** [comment]
It looks like you're using a 0.7.8 config.plist with OpenCore version 0.7.9   
You won't find any errors in your config.plist since you're missing the new fields, you can add them manually or use the 'M' command to have octool merge them in for you.  
Lastly, octool doesn't make a log file, there didn't seem to be much need for it.
